spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fmmall?characterEncoding=utf-8
      username: root
      password: root222333
  devtools:
    # 热部署配置
    restart:
      enabled: true
      # 设置重启的目录，添加目录的文件需要restart
      additional-paths: src/main/java
      # 解决项目自动重新编译后接口报404的问题
      poll-interval: 3000
      quiet-period: 1000

http:
  port: 8081

mybatis:
  mapper-locations: classpath:mappers/*.xml
  # 同beans中的实体包一致
  type-aliases-package: com.tanhua.fmmall.entity
  configuration:
    ## 下划线转驼峰配置
    map-underscore-to-camel-case: true

# 设置项目启动的端口号
server:
  port: 8080
  tomcat:
    #uri地址编码为UTF-8解决传值为中文时乱码
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
  # 开启https,配置跟证书对应
  ssl:
    enabled: true
    key-store: classpath:tanhua233.xyz.jks
    key-store-type: JKS
    key-store-password: cb19cy0s6o